import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import type { ProjectMeta, ProjectMetadata } from './types.js';

export const DATA_ROOT = process.env.PI_WEBUI_DATA
  ? path.resolve(process.env.PI_WEBUI_DATA)
  : path.resolve(import.meta.dirname, '../../data');

export const PROJECTS_ROOT = path.join(DATA_ROOT, 'projects');

/** Directories that never appear in file listings, exports or previews. */
export const HIDDEN_DIRS = new Set(['.webui', '.pi', 'node_modules', '.git']);

const FORBIDDEN_SEGMENT = /^$|^\.\.?$/;
/** 导入/写入禁止触碰的元数据目录（等效参照的 .live-artifacts 保留段）。 */
const RESERVED_PROJECT_FILE_SEGMENTS = new Set(['.webui', '.pi']);

export function projectDir(id: string): string {
  // ids are generated by us (hex), but validate to keep path joins safe
  if (!/^[a-zA-Z0-9_-]+$/.test(id)) throw new Error(`invalid project id: ${id}`);
  return path.join(PROJECTS_ROOT, id);
}

function metaPath(id: string): string {
  return path.join(projectDir(id), '.webui', 'meta.json');
}

export function listProjects(): ProjectMeta[] {
  let entries: fs.Dirent[];
  try {
    entries = fs.readdirSync(PROJECTS_ROOT, { withFileTypes: true });
  } catch {
    return [];
  }
  const projects: ProjectMeta[] = [];
  for (const entry of entries) {
    if (!entry.isDirectory()) continue;
    try {
      const meta = JSON.parse(fs.readFileSync(metaPath(entry.name), 'utf8')) as ProjectMeta;
      projects.push(meta);
    } catch {
      // Directory without metadata — ignore.
    }
  }
  return projects.sort(
    (a, b) => (b.updatedAt ?? b.createdAt) - (a.updatedAt ?? a.createdAt),
  );
}

export function getProject(id: string): ProjectMeta | null {
  try {
    return JSON.parse(fs.readFileSync(metaPath(id), 'utf8')) as ProjectMeta;
  } catch {
    return null;
  }
}

export type CreateProjectExtra = {
  id?: string;
  skillId?: string | null;
  pendingPrompt?: string | null;
  metadata?: ProjectMetadata;
};

export function createProject(
  name: string,
  model: string | null = null,
  extra: CreateProjectExtra = {},
): ProjectMeta {
  const id = extra.id ?? crypto.randomBytes(6).toString('hex');
  const now = Date.now();
  const meta: ProjectMeta = {
    id,
    name: name.trim() || '未命名项目',
    createdAt: now,
    updatedAt: now,
    model,
    skillId: extra.skillId ?? null,
    pendingPrompt: extra.pendingPrompt ?? null,
    metadata: extra.metadata ?? { kind: 'prototype' },
  };
  fs.mkdirSync(path.join(projectDir(id), '.webui'), { recursive: true });
  fs.writeFileSync(metaPath(id), JSON.stringify(meta, null, 2));
  return meta;
}

/** metadata 只在创建/导入时设置，不支持 PATCH 修改。 */
export type ProjectMetaPatch = {
  name?: string;
  model?: string | null;
  thinking?: string | null;
  instructions?: string | null;
  skillId?: string | null;
  pendingPrompt?: string | null;
};

/** 部分更新项目 meta；undefined 字段不动，null 表示清除；name 仅接受非空字符串。 */
export function updateProject(id: string, patch: ProjectMetaPatch): ProjectMeta | null {
  const meta = getProject(id);
  if (!meta) return null;
  const next: ProjectMeta = { ...meta };
  for (const key of ['model', 'thinking', 'instructions', 'skillId', 'pendingPrompt'] as const) {
    if (patch[key] !== undefined) next[key] = patch[key];
  }
  if (typeof patch.name === 'string' && patch.name.trim()) next.name = patch.name.trim();
  next.updatedAt = Date.now();
  fs.writeFileSync(metaPath(id), JSON.stringify(next, null, 2));
  return next;
}

/** 仅刷新 updatedAt（聊天回合落盘 / 文件变更时调用）。项目不存在时静默忽略。 */
export function touchProject(id: string): void {
  const meta = getProject(id);
  if (!meta) return;
  meta.updatedAt = Date.now();
  fs.writeFileSync(metaPath(id), JSON.stringify(meta, null, 2));
}

export function deleteProject(id: string): void {
  fs.rmSync(projectDir(id), { recursive: true, force: true });
}

/** 校验并归一化 zip/上传里的相对路径（移植参照 validateProjectPath）。 */
export function validateProjectPath(raw: unknown): string {
  if (typeof raw !== 'string' || !raw.trim()) {
    throw new Error('invalid file name');
  }
  const normalized = raw.replace(/\\/g, '/');
  if (raw.includes('\0') || /^[A-Za-z]:/.test(normalized) || normalized.startsWith('/')) {
    throw new Error('invalid file name');
  }
  const parts = normalized.split('/').filter(Boolean);
  if (parts.length === 0 || parts.some((p) => FORBIDDEN_SEGMENT.test(p))) {
    throw new Error('invalid file name');
  }
  if (parts.some((part) => RESERVED_PROJECT_FILE_SEGMENTS.has(part))) {
    throw new Error('reserved project path');
  }
  return parts.join('/');
}

/**
 * multer/busboy 把非 ASCII 文件名按 latin1 解码；若字节序列实为 UTF-8 则修复。
 * 已是正确 Unicode（含 >0xFF 码点）的输入原样返回（移植参照 decodeMultipartFilename）。
 */
export function decodeMultipartFilename(name: string): string {
  if (!name || typeof name !== 'string') return name ?? '';
  for (let i = 0; i < name.length; i++) {
    if (name.charCodeAt(i) > 0xff) return name;
  }
  const buf = Buffer.from(name, 'latin1');
  const utf8 = buf.toString('utf8');
  return Buffer.from(utf8, 'utf8').equals(buf) ? utf8 : name;
}

/**
 * Resolve a request path inside a project directory, rejecting traversal.
 * Returns the absolute path, or null if it escapes the project root.
 */
export function safeResolve(id: string, relPath: string): string | null {
  const root = projectDir(id);
  const resolved = path.resolve(root, relPath.replace(/^\/+/, ''));
  if (resolved !== root && !resolved.startsWith(root + path.sep)) return null;
  return resolved;
}

export type FileEntry = { path: string; size: number };

/** Flat list of project files (relative paths), hidden dirs excluded. */
export function listFiles(id: string): FileEntry[] {
  const root = projectDir(id);
  const out: FileEntry[] = [];
  const walk = (dir: string) => {
    let entries: fs.Dirent[];
    try {
      entries = fs.readdirSync(dir, { withFileTypes: true });
    } catch {
      return;
    }
    for (const entry of entries) {
      // 对齐 open-design collectFiles：列表中隐藏全部点文件/点目录。
      if (entry.name.startsWith('.')) continue;
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        if (HIDDEN_DIRS.has(entry.name)) continue;
        walk(full);
      } else if (entry.isFile()) {
        const rel = path.relative(root, full);
        if (rel.split(path.sep).some((seg) => HIDDEN_DIRS.has(seg))) continue;
        out.push({ path: rel.split(path.sep).join('/'), size: fs.statSync(full).size });
      }
    }
  };
  walk(root);
  return out.sort((a, b) => a.path.localeCompare(b.path));
}
