import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import type { ChatMessage, ProjectMeta } from './types.js';

export const DATA_ROOT = process.env.PI_WEBUI_DATA
  ? path.resolve(process.env.PI_WEBUI_DATA)
  : path.resolve(import.meta.dirname, '../../data');

export const PROJECTS_ROOT = path.join(DATA_ROOT, 'projects');

/** Directories that never appear in file listings, exports or previews. */
export const HIDDEN_DIRS = new Set(['.webui', '.pi', 'node_modules', '.git']);

export function projectDir(id: string): string {
  // ids are generated by us (hex), but validate to keep path joins safe
  if (!/^[a-zA-Z0-9_-]+$/.test(id)) throw new Error(`invalid project id: ${id}`);
  return path.join(PROJECTS_ROOT, id);
}

function metaPath(id: string): string {
  return path.join(projectDir(id), '.webui', 'meta.json');
}

function historyPath(id: string): string {
  return path.join(projectDir(id), '.webui', 'history.json');
}

export function listProjects(): ProjectMeta[] {
  let entries: fs.Dirent[];
  try {
    entries = fs.readdirSync(PROJECTS_ROOT, { withFileTypes: true });
  } catch {
    return [];
  }
  const projects: ProjectMeta[] = [];
  for (const entry of entries) {
    if (!entry.isDirectory()) continue;
    try {
      const meta = JSON.parse(fs.readFileSync(metaPath(entry.name), 'utf8')) as ProjectMeta;
      projects.push(meta);
    } catch {
      // Directory without metadata — ignore.
    }
  }
  return projects.sort((a, b) => b.createdAt - a.createdAt);
}

export function getProject(id: string): ProjectMeta | null {
  try {
    return JSON.parse(fs.readFileSync(metaPath(id), 'utf8')) as ProjectMeta;
  } catch {
    return null;
  }
}

export function createProject(name: string, model: string | null = null): ProjectMeta {
  const id = crypto.randomBytes(6).toString('hex');
  const meta: ProjectMeta = { id, name: name.trim() || '未命名项目', createdAt: Date.now(), model };
  fs.mkdirSync(path.join(projectDir(id), '.webui'), { recursive: true });
  fs.writeFileSync(metaPath(id), JSON.stringify(meta, null, 2));
  fs.writeFileSync(historyPath(id), '[]');
  return meta;
}

export function deleteProject(id: string): void {
  fs.rmSync(projectDir(id), { recursive: true, force: true });
}

export function readHistory(id: string): ChatMessage[] {
  try {
    return JSON.parse(fs.readFileSync(historyPath(id), 'utf8')) as ChatMessage[];
  } catch {
    return [];
  }
}

export function appendHistory(id: string, message: ChatMessage): void {
  const history = readHistory(id);
  history.push(message);
  fs.writeFileSync(historyPath(id), JSON.stringify(history, null, 2));
}

/**
 * Resolve a request path inside a project directory, rejecting traversal.
 * Returns the absolute path, or null if it escapes the project root.
 */
export function safeResolve(id: string, relPath: string): string | null {
  const root = projectDir(id);
  const resolved = path.resolve(root, relPath.replace(/^\/+/, ''));
  if (resolved !== root && !resolved.startsWith(root + path.sep)) return null;
  return resolved;
}

export type FileEntry = { path: string; size: number };

/** Flat list of project files (relative paths), hidden dirs excluded. */
export function listFiles(id: string): FileEntry[] {
  const root = projectDir(id);
  const out: FileEntry[] = [];
  const walk = (dir: string) => {
    let entries: fs.Dirent[];
    try {
      entries = fs.readdirSync(dir, { withFileTypes: true });
    } catch {
      return;
    }
    for (const entry of entries) {
      if (entry.name.startsWith('.DS_Store')) continue;
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        if (HIDDEN_DIRS.has(entry.name)) continue;
        walk(full);
      } else if (entry.isFile()) {
        const rel = path.relative(root, full);
        if (rel.split(path.sep).some((seg) => HIDDEN_DIRS.has(seg))) continue;
        out.push({ path: rel.split(path.sep).join('/'), size: fs.statSync(full).size });
      }
    }
  };
  walk(root);
  return out.sort((a, b) => a.path.localeCompare(b.path));
}
